"use client";

import { useState, useMemo } from "react";
import useCopyToast from "@/app/hooks/useCopyToast";

interface Redirect {
  id: number;
  from: string;
  to: string;
  type: "301" | "302";
}

export default function HtaccessGeneratorPage() {
  const [forceHttps, setForceHttps] = useState(true);
  const [forceWww, setForceWww] = useState<"none" | "add" | "remove">("none");
  const [removeTrailingSlash, setRemoveTrailingSlash] = useState(false);
  const [enableGzip, setEnableGzip] = useState(true);
  const [enableCaching, setEnableCaching] = useState(true);
  const [cacheDays, setCacheDays] = useState(30);
  const [securityHeaders, setSecurityHeaders] = useState(true);
  const [blockHotlinking, setBlockHotlinking] = useState(false);
  const [hotlinkDomain, setHotlinkDomain] = useState("example.com");
  const [customErrorPages, setCustomErrorPages] = useState(false);
  const [error404, setError404] = useState("/404.html");
  const [error500, setError500] = useState("/500.html");
  const [redirects, setRedirects] = useState<Redirect[]>([]);
  const [nextId, setNextId] = useState(1);
  const { copy, Toast } = useCopyToast();

  const addRedirect = () => {
    setRedirects([...redirects, { id: nextId, from: "/old-page", to: "/new-page", type: "301" }]);
    setNextId(nextId + 1);
  };

  const removeRedirect = (id: number) => {
    setRedirects(redirects.filter((r) => r.id !== id));
  };

  const updateRedirect = (id: number, field: keyof Redirect, value: string) => {
    setRedirects(redirects.map((r) => (r.id === id ? { ...r, [field]: value } : r)));
  };

  const output = useMemo(() => {
    const lines: string[] = [];
    lines.push("# Generated by DevKit .htaccess Generator");
    lines.push("# https://tools.elunari.uk/htaccess-generator");
    lines.push("");

    if (forceHttps) {
      lines.push("# Force HTTPS");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTPS} off");
      lines.push("RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
      lines.push("");
    }

    if (forceWww === "add") {
      lines.push("# Force www");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTP_HOST} !^www\\. [NC]");
      lines.push("RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
      lines.push("");
    } else if (forceWww === "remove") {
      lines.push("# Remove www");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]");
      lines.push("RewriteRule ^(.*)$ https://%1%{REQUEST_URI} [L,R=301]");
      lines.push("");
    }

    if (removeTrailingSlash) {
      lines.push("# Remove trailing slash");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{REQUEST_FILENAME} !-d");
      lines.push("RewriteRule ^(.*)/$ /$1 [L,R=301]");
      lines.push("");
    }

    if (redirects.length > 0) {
      lines.push("# Redirects");
      for (const r of redirects) {
        lines.push(`Redirect ${r.type} ${r.from} ${r.to}`);
      }
      lines.push("");
    }

    if (enableGzip) {
      lines.push("# Enable Gzip Compression");
      lines.push("<IfModule mod_deflate.c>");
      lines.push("  AddOutputFilterByType DEFLATE text/html");
      lines.push("  AddOutputFilterByType DEFLATE text/css");
      lines.push("  AddOutputFilterByType DEFLATE text/javascript");
      lines.push("  AddOutputFilterByType DEFLATE application/javascript");
      lines.push("  AddOutputFilterByType DEFLATE application/json");
      lines.push("  AddOutputFilterByType DEFLATE application/xml");
      lines.push("  AddOutputFilterByType DEFLATE image/svg+xml");
      lines.push("</IfModule>");
      lines.push("");
    }

    if (enableCaching) {
      const seconds = cacheDays * 86400;
      lines.push("# Browser Caching");
      lines.push("<IfModule mod_expires.c>");
      lines.push("  ExpiresActive On");
      lines.push(`  ExpiresDefault "access plus ${cacheDays} days"`);
      lines.push(`  ExpiresByType image/jpeg "access plus ${cacheDays} days"`);
      lines.push(`  ExpiresByType image/png "access plus ${cacheDays} days"`);
      lines.push(`  ExpiresByType image/gif "access plus ${cacheDays} days"`);
      lines.push(`  ExpiresByType image/svg+xml "access plus ${cacheDays} days"`);
      lines.push(`  ExpiresByType text/css "access plus ${cacheDays} days"`);
      lines.push(`  ExpiresByType application/javascript "access plus ${cacheDays} days"`);
      lines.push("</IfModule>");
      lines.push("");
      lines.push("<IfModule mod_headers.c>");
      lines.push(`  Header set Cache-Control "max-age=${seconds}, public"`);
      lines.push("</IfModule>");
      lines.push("");
    }

    if (securityHeaders) {
      lines.push("# Security Headers");
      lines.push("<IfModule mod_headers.c>");
      lines.push('  Header set X-Content-Type-Options "nosniff"');
      lines.push('  Header set X-Frame-Options "SAMEORIGIN"');
      lines.push('  Header set X-XSS-Protection "1; mode=block"');
      lines.push('  Header set Referrer-Policy "strict-origin-when-cross-origin"');
      lines.push('  Header set Permissions-Policy "camera=(), microphone=(), geolocation=()"');
      lines.push("</IfModule>");
      lines.push("");
    }

    if (blockHotlinking && hotlinkDomain) {
      lines.push("# Block Hotlinking");
      lines.push("RewriteEngine On");
      lines.push(`RewriteCond %{HTTP_REFERER} !^$`);
      lines.push(`RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${hotlinkDomain.replace(".", "\\.")} [NC]`);
      lines.push("RewriteRule \\.(jpg|jpeg|png|gif|webp|svg)$ - [F,NC,L]");
      lines.push("");
    }

    if (customErrorPages) {
      lines.push("# Custom Error Pages");
      if (error404) lines.push(`ErrorDocument 404 ${error404}`);
      if (error500) lines.push(`ErrorDocument 500 ${error500}`);
      lines.push("");
    }

    return lines.join("\n").trim();
  }, [
    forceHttps,
    forceWww,
    removeTrailingSlash,
    enableGzip,
    enableCaching,
    cacheDays,
    securityHeaders,
    blockHotlinking,
    hotlinkDomain,
    customErrorPages,
    error404,
    error500,
    redirects,
  ]);

  const Toggle = ({ label, checked, onChange }: { label: string; checked: boolean; onChange: (v: boolean) => void }) => (
    <label
      style={{
        display: "flex",
        alignItems: "center",
        gap: 8,
        fontSize: "0.88rem",
        cursor: "pointer",
        padding: "6px 0",
      }}
    >
      <input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} />
      {label}
    </label>
  );

  return (
    <main style={{ maxWidth: 960, margin: "0 auto", padding: "2rem 1rem" }}>
      <h1 style={{ fontSize: "1.6rem", fontWeight: 700, marginBottom: 4 }}>
        .htaccess Generator
      </h1>
      <p style={{ color: "var(--muted)", marginBottom: "1.5rem", fontSize: "0.95rem" }}>
        Generate Apache .htaccess rules for redirects, caching, compression, and security headers.
      </p>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.5rem" }}>
        {/* Controls */}
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          <div
            style={{
              padding: "0.8rem",
              borderRadius: 8,
              border: "1px solid var(--border)",
              background: "var(--surface)",
            }}
          >
            <div style={{ fontWeight: 600, fontSize: "0.88rem", marginBottom: 8 }}>URL Handling</div>
            <Toggle label="Force HTTPS" checked={forceHttps} onChange={setForceHttps} />
            <div style={{ display: "flex", alignItems: "center", gap: 8, fontSize: "0.85rem", padding: "6px 0" }}>
              <span>WWW:</span>
              {(["none", "add", "remove"] as const).map((v) => (
                <label key={v} style={{ display: "flex", alignItems: "center", gap: 3, cursor: "pointer" }}>
                  <input
                    type="radio"
                    checked={forceWww === v}
                    onChange={() => setForceWww(v)}
                  />
                  {v === "none" ? "No change" : v === "add" ? "Force www" : "Remove www"}
                </label>
              ))}
            </div>
            <Toggle label="Remove trailing slash" checked={removeTrailingSlash} onChange={setRemoveTrailingSlash} />
          </div>

          <div
            style={{
              padding: "0.8rem",
              borderRadius: 8,
              border: "1px solid var(--border)",
              background: "var(--surface)",
            }}
          >
            <div style={{ fontWeight: 600, fontSize: "0.88rem", marginBottom: 8 }}>Performance</div>
            <Toggle label="Enable Gzip compression" checked={enableGzip} onChange={setEnableGzip} />
            <Toggle label="Browser caching" checked={enableCaching} onChange={setEnableCaching} />
            {enableCaching && (
              <label style={{ fontSize: "0.82rem", display: "flex", alignItems: "center", gap: 6, paddingLeft: 24 }}>
                Cache duration:
                <input
                  type="number"
                  value={cacheDays}
                  onChange={(e) => setCacheDays(Number(e.target.value))}
                  min={1}
                  max={365}
                  style={{
                    width: 55,
                    padding: "3px 6px",
                    fontSize: "0.82rem",
                    border: "1px solid var(--border)",
                    borderRadius: 6,
                    background: "var(--surface)",
                    color: "var(--foreground)",
                    textAlign: "center",
                  }}
                />
                days
              </label>
            )}
          </div>

          <div
            style={{
              padding: "0.8rem",
              borderRadius: 8,
              border: "1px solid var(--border)",
              background: "var(--surface)",
            }}
          >
            <div style={{ fontWeight: 600, fontSize: "0.88rem", marginBottom: 8 }}>Security</div>
            <Toggle label="Security headers" checked={securityHeaders} onChange={setSecurityHeaders} />
            <Toggle label="Block hotlinking" checked={blockHotlinking} onChange={setBlockHotlinking} />
            {blockHotlinking && (
              <label style={{ fontSize: "0.82rem", display: "flex", alignItems: "center", gap: 6, paddingLeft: 24 }}>
                Your domain:
                <input
                  type="text"
                  value={hotlinkDomain}
                  onChange={(e) => setHotlinkDomain(e.target.value)}
                  style={{
                    width: 150,
                    padding: "3px 6px",
                    fontSize: "0.82rem",
                    border: "1px solid var(--border)",
                    borderRadius: 6,
                    background: "var(--surface)",
                    color: "var(--foreground)",
                  }}
                />
              </label>
            )}
            <Toggle label="Custom error pages" checked={customErrorPages} onChange={setCustomErrorPages} />
            {customErrorPages && (
              <div style={{ paddingLeft: 24, display: "flex", flexDirection: "column", gap: 4 }}>
                <label style={{ fontSize: "0.82rem", display: "flex", alignItems: "center", gap: 6 }}>
                  404:
                  <input
                    type="text"
                    value={error404}
                    onChange={(e) => setError404(e.target.value)}
                    style={{
                      width: 150,
                      padding: "3px 6px",
                      fontSize: "0.82rem",
                      fontFamily: "monospace",
                      border: "1px solid var(--border)",
                      borderRadius: 6,
                      background: "var(--surface)",
                      color: "var(--foreground)",
                    }}
                  />
                </label>
                <label style={{ fontSize: "0.82rem", display: "flex", alignItems: "center", gap: 6 }}>
                  500:
                  <input
                    type="text"
                    value={error500}
                    onChange={(e) => setError500(e.target.value)}
                    style={{
                      width: 150,
                      padding: "3px 6px",
                      fontSize: "0.82rem",
                      fontFamily: "monospace",
                      border: "1px solid var(--border)",
                      borderRadius: 6,
                      background: "var(--surface)",
                      color: "var(--foreground)",
                    }}
                  />
                </label>
              </div>
            )}
          </div>

          {/* Redirects */}
          <div
            style={{
              padding: "0.8rem",
              borderRadius: 8,
              border: "1px solid var(--border)",
              background: "var(--surface)",
            }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
              <span style={{ fontWeight: 600, fontSize: "0.88rem" }}>Redirects</span>
              <button className="btn" onClick={addRedirect} style={{ fontSize: "0.75rem", padding: "3px 10px" }}>
                + Add
              </button>
            </div>
            {redirects.map((r) => (
              <div
                key={r.id}
                style={{
                  display: "flex",
                  gap: 6,
                  alignItems: "center",
                  marginBottom: 6,
                  fontSize: "0.8rem",
                }}
              >
                <select
                  value={r.type}
                  onChange={(e) => updateRedirect(r.id, "type", e.target.value)}
                  style={{
                    padding: "3px 4px",
                    fontSize: "0.78rem",
                    border: "1px solid var(--border)",
                    borderRadius: 4,
                    background: "var(--surface)",
                    color: "var(--foreground)",
                  }}
                >
                  <option value="301">301</option>
                  <option value="302">302</option>
                </select>
                <input
                  type="text"
                  value={r.from}
                  onChange={(e) => updateRedirect(r.id, "from", e.target.value)}
                  placeholder="/old"
                  style={{
                    flex: 1,
                    padding: "3px 6px",
                    fontSize: "0.78rem",
                    fontFamily: "monospace",
                    border: "1px solid var(--border)",
                    borderRadius: 4,
                    background: "var(--surface)",
                    color: "var(--foreground)",
                  }}
                />
                <span style={{ color: "var(--muted)" }}>→</span>
                <input
                  type="text"
                  value={r.to}
                  onChange={(e) => updateRedirect(r.id, "to", e.target.value)}
                  placeholder="/new"
                  style={{
                    flex: 1,
                    padding: "3px 6px",
                    fontSize: "0.78rem",
                    fontFamily: "monospace",
                    border: "1px solid var(--border)",
                    borderRadius: 4,
                    background: "var(--surface)",
                    color: "var(--foreground)",
                  }}
                />
                <button
                  onClick={() => removeRedirect(r.id)}
                  style={{
                    background: "none",
                    border: "none",
                    color: "#ef4444",
                    cursor: "pointer",
                    fontSize: "0.85rem",
                    padding: "0 4px",
                  }}
                >
                  x
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Output */}
        <div>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginBottom: 6,
            }}
          >
            <span style={{ fontSize: "0.82rem", fontWeight: 600 }}>.htaccess Output</span>
            <button className="btn" onClick={() => copy(output)} style={{ fontSize: "0.75rem", padding: "3px 10px" }}>
              Copy
            </button>
          </div>
          <pre
            style={{
              minHeight: 500,
              padding: "0.8rem",
              borderRadius: 8,
              border: "1px solid var(--border)",
              background: "var(--surface)",
              color: "var(--foreground)",
              fontFamily: "monospace",
              fontSize: "0.78rem",
              lineHeight: 1.5,
              whiteSpace: "pre-wrap",
              overflow: "auto",
              margin: 0,
            }}
          >
            {output}
          </pre>
        </div>
      </div>

      <Toast />
    </main>
  );
}
