import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://tools.elunari.uk";
  const tools = [
    "",
    "/json-formatter",
    "/base64",
    "/url-encoder",
    "/uuid-generator",
    "/hash-generator",
    "/jwt-decoder",
    "/color-converter",
    "/regex-tester",
    "/lorem-ipsum",
    "/diff-checker",
    "/markdown-preview",
    "/timestamp-converter",
    "/css-minifier",
    "/html-entity-encoder",
    "/word-counter",
    "/text-case-converter",
    "/password-generator",
    "/json-to-csv",
    "/number-base-converter",
    "/sql-formatter",
    "/cron-parser",
    "/yaml-to-json",
    "/image-to-base64",
    "/html-to-markdown",
    "/text-sort-dedupe",
    "/slug-generator",
    "/chmod-calculator",
    "/http-status-codes",
    "/string-escape",
    "/ip-subnet-calculator",
    "/qr-code-generator",
    "/json-path-finder",
    "/ascii-table",
    "/box-shadow-generator",
    "/toml-to-json",
    "/gradient-generator",
    "/flexbox-playground",
    "/meta-tag-generator",
    "/jwt-generator",
    "/svg-to-css",
    "/grid-generator",
    "/border-radius-generator",
    "/text-to-binary",
    "/json-schema-validator",
    "/color-palette-generator",
    "/aspect-ratio-calculator",
    "/csv-to-json",
    "/html-preview",
    "/base-converter",
    "/pixel-to-rem",
    "/http-headers",
    "/css-units-converter",
    "/data-uri-generator",
    "/tailwind-converter",
    "/emoji-picker",
    "/json-compare",
    "/og-preview",
    "/git-commands",
    "/placeholder-image",
    "/crontab-generator",
    "/css-clip-path",
    "/html-table-generator",
    "/json-tree-viewer",
    "/text-to-handwriting",
    "/url-parser",
    "/character-counter",
    "/css-animation-generator",
    "/env-generator",
    "/image-compressor",
    "/js-minifier",
    "/privacy",
  ];

  return tools.map((path) => ({
    url: `${base}${path}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: path === "" ? 1 : 0.8,
  }));
}
